import { APP_EXT } from '@collections/constants';
import { FileRoute } from '@collections/enums';

import '@routes/credential-routes';
import '@routes/icon-routes';
import '@routes/launch-routes';
import '@routes/shortcut-routes';

import { app, BrowserWindow, dialog, ipcMain } from 'electron';

// This allows TypeScript to pick up constants auto-generated by Forge's Webpack plugin
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
    const isDev = process.env.NODE_ENV === 'development';

    mainWindow = new BrowserWindow({
        fullscreen: true,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            contextIsolation: true,
            nodeIntegration: false,
            webviewTag: true,
        },
    });

    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    if (isDev) mainWindow.webContents.openDevTools();
};

app.on('ready', createWindow);

ipcMain.handle(FileRoute.OPEN_DIALOG, async () => {
    const result = await dialog.showOpenDialog(mainWindow!, {
        properties: ['openFile'],
        filters: [{ name: 'Executables', extensions: APP_EXT }],
    });

    if (!result.canceled && result.filePaths.length > 0) {
        return result.filePaths[0];
    }
    return null;
});
